source 'http://rubygems.org'

gem 'rails', '4.0.2'
gem 'mysql2', '~> 0.3.13'
gem 'devise', '~> 3.2.2'
gem 'omniauth', '~> 1.1.4'
gem 'omniauth-google-oauth2', '~> 0.2.2'
gem 'cancan', '= 1.6.7'
gem 'squeel', '~> 1.1.0'
gem 'sentient_model', '~> 1.0.4'
gem 'userstamp', '~> 2.0.2', github: 'kimkong/userstamp'
gem 'validates_hostname', '~> 1.0.0', github: 'KimNorgaard/validates_hostname'
gem 'nilify_blanks', '~> 1.0.2'
gem 'rails_config', '~> 0.3.3'
gem 'rails-settings-cached', '~> 0.3.1'
gem 'active-model-email-validator', '~> 1.0.2'
gem 'mail_form', '~> 1.5.0'
gem 'switch_user', '~> 0.9.3'
gem 'simple_form', '~> 3.0.0'
gem 'concerned_with', '~> 0.1.0'
gem 'navigasmic', '~> 0.5.6', github: 'jejacks0n/navigasmic',
  tag: 'v0.5.6', ref: '1ffe437f279657c6fb87bb4b0215eb723df4ea7a'
gem 'acts_as_nested_interval', '~> 0.1.0'
gem 'seedbank', '~> 0.3.0'
gem 'unicorn', '~> 4.6.3'
gem 'sass-rails', '~> 4.0.0'
gem 'compass-rails', '~> 1.1.0'
gem 'bootstrap-sass', '~> 3.0.3.0'
gem 'font-awesome-rails', '~> 4.0.3.0'
gem 'webshims-rails', '~> 1.11.1'
gem 'detect_timezone_rails', '~> 0.0.3'
gem 'nprogress-rails', '~> 0.1.2.2'
gem 'animate-rails', '~> 1.0.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'uglifier', '~> 2.3.1'
gem 'oily_png', '~> 1.1.0'
gem 'therubyracer', '~> 0.12.0'
gem 'jquery-rails', '~> 3.0.4'
gem 'jquery-ui-rails', '~> 4.1.0'
gem 'dalli', '~> 2.6.2'
gem 'json', '~> 1.8.0'
gem 'active_scaffold', '~> 3.4.0.rc', 
  github: 'clyfe/active_scaffold',
  branch: 'fix-always-use-build_associated'
#  path: '/home/clyfe/dev/active_scaffold'
#  github: 'activescaffold/active_scaffold'
gem 'turbolinks', '~> 2.1.0'
gem 'faker','~> 1.2.0'
gem 'factory_girl_rails', '~> 4.3.0'
gem 'rails_admin', '~> 0.6.0'
# gem 'jquery-cookie-rails', '~> 1.3.1'
# gem 'foreigner', '~> 1.4.2

group :development do
  gem 'quiet_assets', '~> 1.0.1'
  gem 'better_errors', '1.1.0'
  gem 'binding_of_caller', '0.7.2'
  gem 'debase', '~> 0.0.7'
  gem 'bullet', '~> 4.7.1'
  gem 'letter_opener', '~> 1.2.0'
  # gem 'byebug', '~> 2.3.1'
  # gem 'ruby-debug-ide', '~> 0.4.18'
  # gem 'mongrel', '>= 1.2.0.pre2'
  # gem 'capistrano', '~> 2.15.5'
  # gem 'capistrano-ext', '~> 1.2.1'
  # gem 'progress_bar', require: false
  # gem 'parallel_tests', '0.15.3'
  # gem 'yaml_db', '0.2.3'
  # gem 'mailcatcher', '0.5.11'
  # gem 'spring', '0.0.10'
  # gem 'figaro', '0.7.0'
end

group :test, :development do
  gem 'rspec-rails', '~> 2.14.0'
  # gem 'sourcify', '~> 0.6.0.rc1'
end

group :test do
  gem 'capybara', '~> 2.2.0'
  gem 'database_rewinder', '~> 0.0.1'
  # gem 'rb-inotify', '~> 0.9.0'
  # gem 'libnotify', '~> 0.8.1'
  # gem 'guard', '1.8.2'
  # gem 'guard-rspec', '3.0.2'
  # gem 'simplecov', '~> 0.7.1', require: false
end
