default_ttl: 3600
min_ttl: 60
ns:
  - ns1.entrydns.net
  - ns2.entrydns.net
#  - ns3.entrydns.net
#  - ns4.entrydns.net
default_prio: 10
host_domains:
  - entrydns.org
protected_hostnames:
  - www
  - mail
  - smtp
  - imap
  - ns[0-9]*
support_mail: "support@entrydns.net"
honeypot: userid
max_domains_per_user: 200
max_records_per_domain: 500
