domain: entrydns.net

# framework
secret_key_base: 0ce1f02a4b3fc4d1a1c8d22973b21e8589e9314dc338294953f0b985e3f44f12c8af74f2d9ba6f7c7bdb736c4efc5ea3f8135e23b1a036d033cd23331383ac75

# deployment
uses_proxy: true

# application
default_ttl: 3600
min_ttl: 60
ns:
  - ns1.entrydns.net
  - ns2.entrydns.net
  - ns3.entrydns.net
#  - ns4.entrydns.net
default_prio: 10
host_domains:
  - entrydns.org
protected_hostnames:
  - www
  - mail
  - smtp
  - imap
  - ns[0-9]*
max_domains_per_user: 200
max_records_per_domain: 500
resolv:
  - 8.8.8.8
  - 8.8.4.4
  
# public
honeypot: userid
support_mail: "support@entrydns.net"
news_link: "http://twitter.com/#!/entrydns"

google_key: 105547277286.apps.googleusercontent.com
google_secret: 7cIdW07UrWUmeb8QFYV4L63k
