domain: entrydns.net

# framework
secret_key_base: [PLACEHOLDER]

# deployment
uses_proxy: true

# application
default_ttl: 3600
min_ttl: 60
ns:
  - ns1.entrydns.net
  - ns2.entrydns.net
  - ns3.entrydns.net
#  - ns4.entrydns.net
default_prio: 10
host_domains:
  - entrydns.org
protected_hostnames:
  - www
  - mail
  - smtp
  - imap
  - ns[0-9]*
max_domains_per_user: 200
max_records_per_domain: 500
resolv:
  - 8.8.8.8
  - 8.8.4.4
  
# public
honeypot: userid
support_mail: "support@entrydns.net"
news_link: "http://twitter.com/#!/entrydns"

google_key: [PLACEHOLDER]
google_secret: [PLACEHOLDER]

ses_access_key_id: [PLACEHOLDER]
ses_secret_access_key: [PLACEHOLDER]
