require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TxtsController do

  # This should return the minimal set of attributes required to create a valid
  # Txt. As you add validations to Txt, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all txts as @txts" do
      txt = Txt.create! valid_attributes
      get :index
      assigns(:txts).should eq([txt])
    end
  end

  describe "GET show" do
    it "assigns the requested txt as @txt" do
      txt = Txt.create! valid_attributes
      get :show, :id => txt.id.to_s
      assigns(:txt).should eq(txt)
    end
  end

  describe "GET new" do
    it "assigns a new txt as @txt" do
      get :new
      assigns(:txt).should be_a_new(Txt)
    end
  end

  describe "GET edit" do
    it "assigns the requested txt as @txt" do
      txt = Txt.create! valid_attributes
      get :edit, :id => txt.id.to_s
      assigns(:txt).should eq(txt)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Txt" do
        expect {
          post :create, :txt => valid_attributes
        }.to change(Txt, :count).by(1)
      end

      it "assigns a newly created txt as @txt" do
        post :create, :txt => valid_attributes
        assigns(:txt).should be_a(Txt)
        assigns(:txt).should be_persisted
      end

      it "redirects to the created txt" do
        post :create, :txt => valid_attributes
        response.should redirect_to(Txt.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved txt as @txt" do
        # Trigger the behavior that occurs when invalid params are submitted
        Txt.any_instance.stub(:save).and_return(false)
        post :create, :txt => {}
        assigns(:txt).should be_a_new(Txt)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Txt.any_instance.stub(:save).and_return(false)
        post :create, :txt => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested txt" do
        txt = Txt.create! valid_attributes
        # Assuming there are no other txts in the database, this
        # specifies that the Txt created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Txt.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => txt.id, :txt => {'these' => 'params'}
      end

      it "assigns the requested txt as @txt" do
        txt = Txt.create! valid_attributes
        put :update, :id => txt.id, :txt => valid_attributes
        assigns(:txt).should eq(txt)
      end

      it "redirects to the txt" do
        txt = Txt.create! valid_attributes
        put :update, :id => txt.id, :txt => valid_attributes
        response.should redirect_to(txt)
      end
    end

    describe "with invalid params" do
      it "assigns the txt as @txt" do
        txt = Txt.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Txt.any_instance.stub(:save).and_return(false)
        put :update, :id => txt.id.to_s, :txt => {}
        assigns(:txt).should eq(txt)
      end

      it "re-renders the 'edit' template" do
        txt = Txt.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Txt.any_instance.stub(:save).and_return(false)
        put :update, :id => txt.id.to_s, :txt => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested txt" do
      txt = Txt.create! valid_attributes
      expect {
        delete :destroy, :id => txt.id.to_s
      }.to change(Txt, :count).by(-1)
    end

    it "redirects to the txts list" do
      txt = Txt.create! valid_attributes
      delete :destroy, :id => txt.id.to_s
      response.should redirect_to(txts_url)
    end
  end

end
